In [1]:
from FinMind.data import DataLoader
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei']
# plt.rcParams['font.sans-serif'] = ['Arial Unicode Ms']

api = DataLoader()

In [2]:
# 取出台灣股市 ETF
df = api.taiwan_stock_info()

2025-12-04 21:41:59.876 | INFO     | FinMind.data.finmind_api:get_data:171 - download Dataset.TaiwanStockInfo, data_id:

In [3]:
Bond_dataframe = df[
    (df["stock_name"].str.contains("債"))
    & (df["stock_name"].str.contains("元大"))
]
Bond_dataframe

     industry_category stock_id  stock_name  type        date
62      上櫃指數股票型基金(ETF)   00871B     元大中國政金債  tpex  2021-03-03
317     上櫃指數股票型基金(ETF)   00721B    元大中國債3-5  tpex  2024-10-16
530     上櫃指數股票型基金(ETF)   00787B  元大10年IG醫療債  tpex  2024-12-30
533     上櫃指數股票型基金(ETF)   00788B  元大10年IG電能債  tpex  2024-12-30
542     上櫃指數股票型基金(ETF)   00786B  元大10年IG銀行債  tpex  2024-12-30
566     上櫃指數股票型基金(ETF)   00720B    元大投資級公司債  tpex  2024-12-30
567     上櫃指數股票型基金(ETF)   00719B     元大美債1-3  tpex  2024-12-30
569     上櫃指數股票型基金(ETF)   00697B    元大美債7-10  tpex  2024-12-30
574     上櫃指數股票型基金(ETF)   00679B     元大美債20年  tpex  2024-12-30
595     上櫃指數股票型基金(ETF)   00751B  元大AAA至A公司債  tpex  2024-12-30
597     上櫃指數股票型基金(ETF)   00870B  元大15年EM主權債  tpex  2024-12-30
604     上櫃指數股票型基金(ETF)   00969B    元大零息超長美債  tpex  2024-12-30
605     上櫃指數股票型基金(ETF)   00968B     元大優息投等債  tpex  2024-12-30
608     上櫃指數股票型基金(ETF)   00967B      元大優息美債  tpex  2024-12-30
753                ETF   00698L  元大美債7-10正2  twse  2025-11-22
754                ETF   00699R  元大美債7-10反1  twse  2025-11-22
2644             上櫃ETF   00786B  元大10年IG銀行債  tpex  2025-12-04
2645             上櫃ETF   00787B  元大10年IG醫療債  tpex  2025-12-04
2646             上櫃ETF   00788B  元大10年IG電能債  tpex  2025-12-04
2672             上櫃ETF   00751B  元大AAA至A公司債  tpex  2025-12-04
2748             上櫃ETF   00870B  元大15年EM主權債  tpex  2025-12-04
2817             上櫃ETF   00719B     元大美債1-3  tpex  2025-12-04
2818             上櫃ETF   00720B    元大投資級公司債  tpex  2025-12-04
2840             上櫃ETF   00679B     元大美債20年  tpex  2025-12-04
2841               ETF   00680L    元大美債20正2  twse  2025-12-04
2842               ETF   00681R    元大美債20反1  twse  2025-12-04
2858             上櫃ETF   00697B    元大美債7-10  tpex  2025-12-04
2991             上櫃ETF   00967B      元大優息美債  tpex  2025-12-04
2992             上櫃ETF   00968B     元大優息投等債  tpex  2025-12-04
2993             上櫃ETF   00969B    元大零息超長美債  tpex  2025-12-04

In [ ]:
ETF_dataframe = df[
    (df["industry_category"].str[:3] == "ETF")
    & (df["stock_name"].str.contains("元大"))
    & (df["stock_id"].str[-1].str.isnumeric())
]
ETF_dataframe

    industry_category stock_id stock_name  type        date
0                 ETF     0050     元大台灣50  twse  2024-11-28
1                 ETF     0051    元大中型100  twse  2024-11-28
3                 ETF     0053       元大電子  twse  2024-11-28
4                 ETF     0054     元大台商50  twse  2024-11-28
5                 ETF     0055   元大MSCI金融  twse  2024-11-28
6                 ETF     0056      元大高股息  twse  2024-11-28
11                ETF     0061      元大寶滬深  twse  2024-11-28
13                ETF   006203   元大MSCI台灣  twse  2024-11-28
16                ETF   006206     元大上證50  twse  2024-11-28
36                ETF    00646   元大S&P500  twse  2024-11-28
51                ETF    00660     元大歐洲50  twse  2024-11-28
52                ETF    00661    元大日經225  twse  2024-11-28
58                ETF    00667       元大韓國  twse  2024-11-28
105               ETF    00713   元大台灣高息低波  twse  2024-11-28
131               ETF    00739  元大MSCI A股  twse  2024-11-28
154               ETF    00762     元大全球AI  twse  2024-11-28
162               ETF    00771  元大US高息特別股  twse  2024-11-28
214               ETF    00850  元大臺灣ESG永續  twse  2024-11-28
225               ETF    00861   元大全球未來通訊  twse  2024-11-28
240               ETF    00876     元大全球5G  twse  2024-11-28
303               ETF    00940   元大台灣價值高息  twse  2024-11-28
327               ETF    00965   元大航太防衛科技  twse  2024-11-28